
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('TEST1','size1','photourl','test1,test2,test3,test4');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('TEST2','size1','photourl','test1,test2,test3,test4');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('TEST3','size1','photourl','test1,test2,test3,test4');

INSERT INTO RESERVE(NAME,REGION) VALUES ('Doñana','Andalucía');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Monfrague National Park','Extremadura');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Birds in Llanos de Caceres','Extremadura');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Cabañeros National Park','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Tablas de Daimiel','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Ruidera Lakes','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Tejera Negra Beech Forest','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Alto Tajo','Castile-La Mancha');

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'TEST1'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Doñana'),
  '2019-06-01',60.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'TEST1'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Birds in Llanos de Caceres'),
  '2019-06-01',10.5);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'TEST1'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Alto Tajo'),
  '2019-07-01',15.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'TEST2'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Doñana'),
  '2019-07-01',40.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'TEST3'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Tablas de Daimiel'),
  '2019-07-01',55.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'TEST3'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Alto Tajo'),
  '2019-06-01',30.0);

