
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('wigeon','Small','photourl','black,white,blue,red');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('teal','Small','photourl','black,blue,white,green');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('greylag goose','Medium','photourl','white,red,green,grey');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('stone-curlew','Big','photourl','red,blue,green,white');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('purple gallinule','Medium','photourl','white,red,green,grey');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('white stork','Big','photourl','black,white,blue,red');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('pochard','Small','photourl','black,white,blue,red');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('white-headed duck','Big','photourl','test1,test2,test3,test4');
INSERT INTO BIRD(NAME,SIZE,PHOTO,COLOUR) VALUES ('gull','Medium','photourl','black,blue,white,green');

INSERT INTO RESERVE(NAME,REGION) VALUES ('Doñana','Andalucía');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Monfrague National Park','Extremadura');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Birds in Llanos de Caceres','Extremadura');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Cabañeros National Park','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Tablas de Daimiel','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Ruidera Lakes','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Tejera Negra Beech Forest','Castile-La Mancha');
INSERT INTO RESERVE(NAME,REGION) VALUES ('Alto Tajo','Castile-La Mancha');

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'wigeon'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Doñana'),
  '2019-06-01',60.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'wigeon'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Cabañeros National Park'),
  '2019-07-20',10.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'wigeon'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Birds in Llanos de Caceres'),
  '2019-07-25',15.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'teal'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Birds in Llanos de Caceres'),
  '2019-06-06',12.5);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'teal'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Doñana'),
  '2019-06-20',55.0);


INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'greylag goose'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Cabañeros National Park'),
  '2019-07-01',15.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'stone-curlew'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Doñana'),
  '2019-07-15',40.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'purple gallinule'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Tablas de Daimiel'),
  '2019-07-20',55.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'white stork'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Alto Tajo'),
  '2019-06-15',30.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'white stork'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Doñana'),
  '2019-06-20',24.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'pochard'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Doñana'),
  '2019-07-04',14.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'white-headed duck'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Ruidera Lakes'),
  '2019-06-18',80.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'white-headed duck'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Tablas de Daimiel'),
  '2019-06-19',5.0);

INSERT INTO BIRD_RESERVE(BIRD_ID, RESERVE_ID, VISIT_DATE, PERCENTAGE) VALUES (
  (SELECT ID FROM BIRD WHERE NAME = 'gull'),
  (SELECT ID FROM RESERVE WHERE NAME = 'Tablas de Daimiel'),
  '2019-07-07',10.0);
